show_author_username:
  type: bool
  default: false
  description:
    en: "Show author usernames instead profile avatars."

show_topic_author_column:
  type: enum
  default: Default
  choices:
    - First
    - Last
    - Default
  description: 
    en: "Show topic authors column first, last or default."
