show_author_username:
  type: bool
  default: false
  description:
    en: "Show author usernames instead profile avatars."

show_topic_author_column:
  type: string
  default: ""
  description: 
    en: "Show topic authors column first, last or default."
