show_author_username:
  type: bool
  default: false
  description:
    en: "Show author usernames instead profile avatars."

show_topic_author_column:
  type: enum
  default: ""
  choices:
    - First
    - Last
  description: 
    en: "Placement of topic authors column."
    
